### ISSUE TITLE
The accuracy of the current versions.txt

### ISSUE THREAD

**Issue by mspykerez** [16BitWonder/NX-Update-Checker#28]
Hi

As I mentioned here https://github.com/blawar/titledb/issues/16 appears there is a problem with blawar's titledb making it not list all updates (at least concerning DLCs) which can be a problem since NX-Update-Checker uses that database to grab its information?

That being said I checked https://github.com/16BitWonder/nx-versions/blob/master/versions.txt and found that some of the DLC updates that are not listed on blawar's titledb versions.txt (the DLC shows there, but not that it has an update available for it) do indeed appear on https://github.com/16BitWonder/nx-versions/blob/master/versions.txt

The concern is that if https://github.com/16BitWonder/nx-versions/blob/master/versions.txt is showing said updates only because the ones I checked are kinda old since that's the ones I know for sure that have an update available for them and at some point in the past also showed on blawar's titledb, meaning that I'm not sure if it is listing recently released updates for all DLCs or not.

My thinking is that https://github.com/16BitWonder/nx-versions/blob/master/versions.txt does not delete anything already there and only adds/replaces existing updates from its list when a more recent one is found and that is probably why it's still showing the ones that mysteriously disappeared from blawar's titledb making me wonder if some recent updates are just not being listed at all in blawar's titledb and consequently https://github.com/16BitWonder/nx-versions/blob/master/versions.txt

That is all assuming that NX-Update-Checker is 100% relying on blawar's titledb to get all its data from and if so I'm not sure how hard would it be to fix this, use a new source or create your own.

**Comment by 16BitWonder** [comment]
nx-versions pulls information from titledb but does not pull solely from versions.txt.
I noticed that DLC versions are not always populated within its versions.txt too but figured to work around it while that is the case.

It pulls from a combination of the files hosted in that repository that do include DLC versions that are otherwise missing in titledb's versions.txt.

Such as 01006A800016F004 with version 2 and 0100876015D75001 with version 1.
As mentioned in the issue you linked to.

**Comment by mspykerez** [comment]
In here https://github.com/blawar/titledb cnmts.json seems to be the file that did not have DLC updates suddenly disappear from it unlike some others... perhaps you are using this one?

In any case my concern is that if blawar's titledb is bugged even further to the point that it's completely missing more recent updates and we don't even know it. I only notice the issue because I was sure that some of the old DLCs I have at one point got updated and I also had those update files and upon deleting some of them [Switch Library Manager](https://github.com/giwty/switch-library-manager) did not report anything missing like it used to.

It's hard to pinpoint if there is anything missing from titledb when there is no other easy way/source to compare to.
There are some sites that list updates but for DLCs it's quite rare, tinfoil.io seems to have them listed but it's a bummer to check manually on the site.

**Comment by 16BitWonder** [comment]
> In here https://github.com/blawar/titledb cnmts.json seems to be the file that did not have DLC updates suddenly disappear from it unlike some others... perhaps you are using this one?

Yes, cnmt.json is one of the files being pulled from.

Switch-Library-Manager does not pull from cnmt.json. What I assume is happening there is that since they're no longer pulling file(s) that have integral DLC info it's showing inconsistent DLC information.

I don't have the additional hardware or time to set up a system of my own to scrape for update data, but I'm confident that (when scraping properly from the repo) titledb provides accurate version info.

**Comment by mspykerez** [comment]
I don't know if you saw it since the issue is 'closed' but I made an afterwards post here https://github.com/16BitWonder/NX-Update-Checker/issues/29#issuecomment-1125433334 and I wonder if you know how to convert https://github.com/16BitWonder/nx-versions/blob/master/versions.txt to be compatible with Switch-Library-Manager or something like that? I don't know how to code and I reported the titledb issue to the devs but they seem MIA.

Looking at the files that Switch-Library-Manager generates it appears it grabs the versions.json from titledb without doing any modifications to it and also think it generates an titles.json file which is not listed on titledb but it's described there how to generate it. Needless to say that both these files are missing some DLC updates, they display information on a different way than versions.txt and I'm not sure which one is used for what.

**Comment by 16BitWonder** [comment]
Apologies, I was drafting a response to your other issue but something else came up.

My personal opinion is that it's redundant to generate nx-versions from titledb info, then convert it into a format that your manager supports.
That then creates an unnecessary external dependency on a middle-man type solution where they could instead change how they're pulling directly from titledb.

From their [settings.go](https://github.com/giwty/switch-library-manager/blob/master/settings/settings.go) and console.go it seems like they're grabbing versions.json and titles.json on boot but not cnmt.json.

I would recommend that in your open issue you mention that cnmt.json holds info they're missing, but if they're MIA it may be in your better interest to find an active fork and mention it there.

**Comment by mspykerez** [comment]
I've mentioned cnmt.json but like you said the dev is MIA so I do not know if it will ever be fixed... there's hope that blawar himself fixes or reverts the versions files to list all missing DLC updates like it use to.

I also checked all the forks but there isn't any updated active fork

If only Switch Library Manager supported https://github.com/16BitWonder/nx-versions/blob/master/versions.txt would be great in the meantime.

**Comment by 16BitWonder** [comment]
That's unfortunate there aren't any active forks.

Respectfully, I'm not really interested in changing how nx-versions is being built to be compatible with someone else's project.
Nor am I looking to troubleshoot someone else's project in a programming language I'm unfamiliar with.
The correct solution here isn't to change what I'm building and point Switch Library Manager to it, but rather fix how it's parsing information from titledb directly.

I'm going to go ahead and close this issue since it seems unrelated to NX-Update-Checker and not an issue nx-versions is experiencing, since it seems to (at this point in time) be pulling accurate DLC information from titledb.

This seems like more of combination of issues where titledb is not including any DLC versions in its versions.json. (I say this because we can see from [settings.go](https://github.com/giwty/switch-library-manager/blob/master/settings/settings.go) that it downloads versions.json, not versions.txt).
And Switch Library Manger is not accommodating for the lack of DLC info in versions.json by referencing cnmts.json too.
